import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

public class LetterCounter {
    static String count(String str) {
        Map<Character, Integer> map = new TreeMap<>();
        Main.CHARS.forEach(c -> map.put(c, 0));
        for (int i = 0; i < str.length(); ++i) {
            map.computeIfPresent(str.charAt(i), (key, oldV) -> oldV + 1);
        }
        StringBuilder builder = new StringBuilder();
        map.forEach((c, i) -> builder.append(c).append(i));
        return builder.toString();
    }
    public static void main(String[] args) {
        System.out.print(count("VXURURTXUXRUVXUXDUBXUBIUYXTOUBMTGXMUVMUXTXUIUMUYMUXIOUOUTUYUVRURDMATUBUYBUGUXBXYYIBYBRBUMUGYOTVTUAUBUMUOIAUATUVMUOIWUIUDXYTXUVMRUBMYURBUBTUVUMBUTUYTXUIRUYUVTUXIBMGBATMUTUVBATXUBIUXTBUXOTUTUBMBTUWUXUIUXAMUXIMTXTUVXUXMUBTUXUXUOBTRAUBMRUGTXUXBUYUMXMUGUBXUMWUBXUBUXROUXMYRVROVGBURXVRUXVUVUGUBTBUAUMIUTYYUXUVMRBMTUMUIXUYBUMROIUOAUTYOIAUMBXMUVUXMXUDMXYBUBMYUXIGMYTMATBVMUBMTITDUMWUWMUXVWURYUAYTOUMUYTRBYBUYUGAXRWUXOURMUBYUTXUXUBUTAYMXBOBUVTUGBIUYBYUVTUYMUABYRGWMVXMITUBARBGBVUMUBVYTMBVXTUBIDOBXUWUVIUDUYAUXUMRUBMUTUOUTBYTUTIMUMUBXTUTUBRTUYMBAOUVIMYUBUXYIBTVTYTBUMTXUOXUYABAMBYUXYVBXMTMYUYXUTBIMXYBUBTOUTUMARYMUBXWODUXUBUMGUBYUAOXYTURUXMUDUYUBXIUYUBUMTAUMBRTBUBOUTBUXUBDBYDTXRUMUAUTVBRUVUIUXMUWMDIVBRURUMUGUBUDYUBMTUTMUVUIBTIXTUBUARTUTYUYGMBYROUTBXBUAIUYVUVUXVBUTVXIXBMWBMWUWUVUYYTWXUTBUBYTUBUVBUTUBYMVTUVUBXAUMAUYBIUTUBMOXURBYUMBWBUYTUYUXUTBYXBXUOTUXUVXGOXUOTOBYXUBUBXAUBTXMGMXURTXBABTBMBOAU"));
    }
}
